import { BookMeta } from "./types";

export const BIBLE_BOOKS_META: BookMeta[] = [
  // ── Old Testament ──
  { id: "gen", name: "Genesis", chapters: 50, testament: "old" },
  { id: "exo", name: "Exodus", chapters: 40, testament: "old" },
  { id: "lev", name: "Leviticus", chapters: 27, testament: "old" },
  { id: "num", name: "Numbers", chapters: 36, testament: "old" },
  { id: "deu", name: "Deuteronomy", chapters: 34, testament: "old" },
  { id: "jos", name: "Joshua", chapters: 24, testament: "old" },
  { id: "jdg", name: "Judges", chapters: 21, testament: "old" },
  { id: "rut", name: "Ruth", chapters: 4, testament: "old" },
  { id: "1sa", name: "1 Samuel", chapters: 31, testament: "old" },
  { id: "2sa", name: "2 Samuel", chapters: 24, testament: "old" },
  { id: "1ki", name: "1 Kings", chapters: 22, testament: "old" },
  { id: "2ki", name: "2 Kings", chapters: 25, testament: "old" },
  { id: "1ch", name: "1 Chronicles", chapters: 29, testament: "old" },
  { id: "2ch", name: "2 Chronicles", chapters: 36, testament: "old" },
  { id: "ezr", name: "Ezra", chapters: 10, testament: "old" },
  { id: "neh", name: "Nehemiah", chapters: 13, testament: "old" },
  { id: "est", name: "Esther", chapters: 10, testament: "old" },
  { id: "job", name: "Job", chapters: 42, testament: "old" },
  { id: "psa", name: "Psalms", chapters: 150, testament: "old" },
  { id: "pro", name: "Proverbs", chapters: 31, testament: "old" },
  { id: "ecc", name: "Ecclesiastes", chapters: 12, testament: "old" },
  { id: "sng", name: "Song of Solomon", chapters: 8, testament: "old" },
  { id: "isa", name: "Isaiah", chapters: 66, testament: "old" },
  { id: "jer", name: "Jeremiah", chapters: 52, testament: "old" },
  { id: "lam", name: "Lamentations", chapters: 5, testament: "old" },
  { id: "ezk", name: "Ezekiel", chapters: 48, testament: "old" },
  { id: "dan", name: "Daniel", chapters: 12, testament: "old" },
  { id: "hos", name: "Hosea", chapters: 14, testament: "old" },
  { id: "jol", name: "Joel", chapters: 3, testament: "old" },
  { id: "amo", name: "Amos", chapters: 9, testament: "old" },
  { id: "oba", name: "Obadiah", chapters: 1, testament: "old" },
  { id: "jon", name: "Jonah", chapters: 4, testament: "old" },
  { id: "mic", name: "Micah", chapters: 7, testament: "old" },
  { id: "nah", name: "Nahum", chapters: 3, testament: "old" },
  { id: "hab", name: "Habakkuk", chapters: 3, testament: "old" },
  { id: "zep", name: "Zephaniah", chapters: 3, testament: "old" },
  { id: "hag", name: "Haggai", chapters: 2, testament: "old" },
  { id: "zec", name: "Zechariah", chapters: 14, testament: "old" },
  { id: "mal", name: "Malachi", chapters: 4, testament: "old" },
  // ── New Testament ──
  { id: "mat", name: "Matthew", chapters: 28, testament: "new" },
  { id: "mrk", name: "Mark", chapters: 16, testament: "new" },
  { id: "luk", name: "Luke", chapters: 24, testament: "new" },
  { id: "jhn", name: "John", chapters: 21, testament: "new" },
  { id: "act", name: "Acts", chapters: 28, testament: "new" },
  { id: "rom", name: "Romans", chapters: 16, testament: "new" },
  { id: "1co", name: "1 Corinthians", chapters: 16, testament: "new" },
  { id: "2co", name: "2 Corinthians", chapters: 13, testament: "new" },
  { id: "gal", name: "Galatians", chapters: 6, testament: "new" },
  { id: "eph", name: "Ephesians", chapters: 6, testament: "new" },
  { id: "php", name: "Philippians", chapters: 4, testament: "new" },
  { id: "col", name: "Colossians", chapters: 4, testament: "new" },
  { id: "1th", name: "1 Thessalonians", chapters: 5, testament: "new" },
  { id: "2th", name: "2 Thessalonians", chapters: 3, testament: "new" },
  { id: "1ti", name: "1 Timothy", chapters: 6, testament: "new" },
  { id: "2ti", name: "2 Timothy", chapters: 4, testament: "new" },
  { id: "tit", name: "Titus", chapters: 3, testament: "new" },
  { id: "phm", name: "Philemon", chapters: 1, testament: "new" },
  { id: "heb", name: "Hebrews", chapters: 13, testament: "new" },
  { id: "jas", name: "James", chapters: 5, testament: "new" },
  { id: "1pe", name: "1 Peter", chapters: 5, testament: "new" },
  { id: "2pe", name: "2 Peter", chapters: 3, testament: "new" },
  { id: "1jn", name: "1 John", chapters: 5, testament: "new" },
  { id: "2jn", name: "2 John", chapters: 1, testament: "new" },
  { id: "3jn", name: "3 John", chapters: 1, testament: "new" },
  { id: "jud", name: "Jude", chapters: 1, testament: "new" },
  { id: "rev", name: "Revelation", chapters: 22, testament: "new" },
];
